version: '3'

services:
  rogastore-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: rogastore-api/api
    ports:
      - 8080:8080
    links:
      - postgres
    depends_on:
      - postgres
      
  postgres:
    image: postgres:13.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - APP_DB_USER=rogastore
      - APP_DB_PASS=rogastore
      - APP_DB_NAME=postgres
    ports:
      - 5000:5432
