create table tb_app (id_app int8 generated by default as identity, description varchar(255), name varchar(255) not null, price numeric(19, 2) not null, category_id int8 not null, primary key (id_app));

alter table if exists tb_app add constraint fk_app_category foreign key (category_id) references tb_category;
